language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "iojs"
before_install:
  - sudo rm /etc/apt/sources.list.d/*.list
  - sudo apt-get update -q
  - sudo apt-get install -y freeglut3-dev mesa-common-dev libudev-dev libxext-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
