#!/usr/local/bin/node

/**
 * Retrieves data stream from Oculus Rift.
 * Warning only works on Windows
 */

var hmd 	= require('node-hmd');
var devices = hmd.getSupportedDevices();

//creating the device manager for the oculus rift
var manager = hmd.createManager('oculusrift');
 
manager.getDeviceInfo(function(err, data) 
{	
	if(err) 
	{
 		console.log('ERR', err.toString());
 		process.exit(1);
 	}
 	console.log(data);

 });

manager.getDeviceOrientation(function(err, data) 
{

 	if(err) 
	{
 		console.log('ERR', err.toString());
 		process.exit(1);
 	}
 	console.log(data);
 });

oculus.discoverSensor();
