#!/usr/local/bin/node

/**
 * Retrieves data stream from Oculus Rift.
 * Warning only works on Windows
 */

var hmd 	= require('node-hmd');
var devices = hmd.getSupportedDevices();
var socket 	= require('dgram').createSocket('udp4');

var manager = hmd.createManager('oculusrift');

function getDeviceOrientation() {
	manager.getDeviceOrientation(function(err, data) {

		if(err) {
			console.log('ERR', err.toString());
			process.exit(1);
		}
		
		var roll;
		var pitch;
		var yall;

		onDeviceOrientdationData(data, getDeviceOrientation);
		
	 	// fs.writeFile('data.txt', roll + "\r\n" + pitch + "\r\n" + yaw + "\r\n");

	});
}

function onDeviceOrientdationData(data, callback) {

	var yaw = data.yaw;
	var pitch = 

	var message = new Buffer(data.yaw + ',' + data.pitch + ',' + data.roll, 'utf-8');

	socket.send(message, 0, message.length, 14552, '192.168.10.102', function(err, bytes) {

	if(err) {
		console.log('error sending message> ' + err);
	} else {
		console.log('message sent...');
	}

	callback.call();

});

}

/**
 * Main function
 */
(function main() {
	getDeviceOrientation();
})();
